Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02396cdd13e9a1257
      InstanceType: t2.micro
      KeyName: node.keypair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello, Developpers is your engineer Lekunga Elizabeth!"
      SecurityGroupIds:
        - sg-01a508bc795920855

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: admin123
      DBInstanceIdentifier: mydb
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - sg-01a508bc795920855

